import Head from 'next/head';
import { Header, Row } from 'src/components';

export default function Home() {
	return (
		<div className='relative h-[200vh]'>
			<Head>
				<title>Home - Sammi</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/logo.svg' />
			</Head>
			<Header />
			<main>
				{/* Hero */}
				<section>
					{/* Row */}
					{/* BigRow */}
					{/* Row */}
					{/* BigRow */}
				</section>
			</main>
		</div>
	);
}
